region:
  name: Mumbai
  roi: [72.77, 19.00, 73.00, 19.30]

dates:
  past: ["2023-06-01", "2023-09-30"]
  recent: ["2024-06-01", "2024-09-30"]

satellite:
  dataset: COPERNICUS/S2_SR_HARMONIZED
  cloud_threshold: 80
  scale: 30

detection:
  ndwi_threshold: 0.3
  pixel_resolution: 30